version: '3.8'

services:
  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ml_data:/data
    environment:
      - LEXICLASS_ENVIRONMENT=production
      - LEXICLASS_CELERY__BROKER_URL=redis://redis:6379/0
      - LEXICLASS_CELERY__RESULT_BACKEND=redis://redis:6379/0
      - LEXICLASS_LOG_LEVEL=INFO
      - LEXICLASS_LOG_FORMAT=json
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      redis:
        condition: service_healthy

volumes:
  redis_data:
    driver: local
  ml_data:
    driver: local
